DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS book;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL
);
CREATE TABLE book{
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titre TEXT NOT NULL,
    auteur TEXT NOT NULL,
    quantite INTEGER NOT NULL
};
CREATE TABLE auteur{
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,id INTEGER PRIMARY KEY AUTOINCREMENT,
    prenom TEXT NOT NULL
};
CREATE TABLE emprunt{
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dateDebut DATE NOT NULL,
    dateFin DATE NOT NULL,
    restitution DATE
}
